using Content.Shared.Imperial.ICCVar;
using Content.Shared.Imperial.ShowPopupOnJoin;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Utility;
using System.Linq;

namespace Content.Client.Imperial.ShowPopupOnJoin.UI;

[GenerateTypedNameReferences]
public sealed partial class PopupWindow : DefaultWindow
{
    [Dependency] private readonly IConfigurationManager _configManager = default!;
    [Dependency] private readonly IUriOpener _uriOpener = default!;

    const int QRPixelSize = 10;

    public PopupWindow(SharedShowPopupOnJoin.PopupContentMessage content)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Title = content.Title;
        TextContent.SetMessage(FormattedMessage.FromMarkup(content.Content));

        Resizable = false;

        var lines = content.QRData.Split('|');
        var imageSize = lines.First().Length;
        SetWidth = imageSize * QRPixelSize + 25;

        foreach (var line in lines)
        {
            var horizontalBox = new BoxContainer()
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal
            };
            foreach (var element in line)
            {
                var pixel = new PanelContainer()
                {
                    SetSize = new(QRPixelSize, QRPixelSize),
                    PanelOverride = new StyleBoxFlat
                    {
                        BackgroundColor = element == '1' ? Color.White : Color.Black,
                    }
                };
                horizontalBox.AddChild(pixel);
            }
            QRContainer.AddChild(horizontalBox);
        }

        NeverShowButton.OnPressed += NeverShow;

        OpenLinkButton.OnPressed += NeverShow;
        OpenLinkButton.OnPressed +=
            e => _uriOpener.OpenUri(_configManager.GetCVar(ICCVars.ShowPopupOnJoin.Link));
    }

    void NeverShow(BaseButton.ButtonEventArgs e)
    {
        _configManager.SetCVar(ICCVars.ShowPopupOnJoin.Enabled, false);
        Close();
    }
}
