using Content.Shared.Imperial.ICCVar;
using Content.Shared.Imperial.ShowPopupOnJoin;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Utility;
using System.Diagnostics;
using System.Linq;
using System.Security.Policy;

namespace Content.Client.Imperial.ShowPopupOnJoin.UI;

[GenerateTypedNameReferences]
public sealed partial class PopupWindow : DefaultWindow
{
    [Dependency] private readonly IConfigurationManager _configManager = default!;
    [Dependency] private readonly IUriOpener _uriOpener = default!;

    public PopupWindow(SharedShowPopupOnJoin.PopupContentMessage content)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Title = content.Title;
        TextContent.SetMessage(content.Content);

        var qrData =
            content.QRData
            .Split("|")
            .Select(line =>
                line.Select(element => element == '1')
            );


        foreach (var line in qrData)
        {
            var horizontalBox = new BoxContainer()
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal
            };
            foreach (var element in line)
            {
                var pixel = new PanelContainer()
                {
                    SetSize = new(10, 10),
                    PanelOverride = new StyleBoxFlat
                    {
                        BackgroundColor = element ? Color.White : Color.Black
                    }
                };
                horizontalBox.AddChild(pixel);
            }
            QRContainer.AddChild(horizontalBox);
        }

        NeverShowButton.OnPressed += NeverShow;

        OpenLinkButton.OnPressed += NeverShow;
        OpenLinkButton.OnPressed +=
            e => _uriOpener.OpenUri(content.Link);
    }

    void NeverShow(BaseButton.ButtonEventArgs e)
    {
        _configManager.SetCVar(ICCVars.ShowPopupOnJoin.Enabled, false);
        Close();
    }
}
